name: ci

on:
  pull_request:
  push:
    branches:
    - master
    - different_repo_test

jobs:
  TestMatrix:
    strategy:
      matrix:
        neovim: [v0.10.0]
        os: ["windows-latest"]
        luaVersion:
        - "5.1"
        include:
          - os: "windows-latest"
            toolchain: "msvc"
            luaVersion: "5.1"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - name: Setup MSVC
      # 'luarocks/gh-actions-lua' step requires msvc to build PUC-Rio Lua
      # versions on Windows (LuaJIT will be built using MinGW/gcc).
      if: ${{ matrix.toolchain == 'msvc' }}
      uses: ilammy/msvc-dev-cmd@v1

    - uses: luarocks/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: luarocks/gh-actions-luarocks@master

    - name: Windows Build
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        luarocks install luafilesystem
        lua -e "require 'lfs'"
