name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main
      - testing_other_packages

jobs:
  test:
    strategy:
      matrix:
        os: ["windows-latest"]
        luaVersion:
        - "5.1"
        include:
          - os: "windows-latest"
            toolchain: "msvc"
            luaVersion: "5.1"

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"

    steps:

    - uses: actions/checkout@v4
      with:
        repository: "lunarmodules/luasystem"

    - name: Setup MSVC
      # the 'hishamhm/gh-actions-lua' step requires msvc to build PuC Rio Lua
      # versions on Windows (LuaJIT will be build using MinGW/gcc).
      if: ${{ matrix.toolchain == 'msvc' }}
      uses: ilammy/msvc-dev-cmd@v1

    - uses: hishamhm/gh-actions-lua@master
      with:
        luaVersion: "5.1"

    - uses: hishamhm/gh-actions-luarocks@v5
      with:
        luarocksVersion: "3.11.0"

    - name: Install mega.logging
      run: |
        luarocks install mega.logging
        lua -e "require 'mega.logging'"

    - name: Install LuaFileSystem
      run: |
        luarocks install luafilesystem
        lua -e "require 'lfs'"
