name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main
      - git_clone_test

jobs:
  test:
    runs-on: ubuntu-latest
    name: "clone test"

    steps:
    - name: git clone - does it work - http
      run: |
        git clone http://github.com/ColinKennedy/mega.logging.git

    - name: git clone - does it work - https
      run: |
        git clone https://github.com/ColinKennedy/mega.logging.git

    - name: git clone - does it work - ssh
      run: |
        git clone git@github.com:ColinKennedy/mega.logging.git
